# Generated by Django 4.2.3 on 2023-08-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("age_group", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("phone_number", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("pricing", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("participants", models.IntegerField(max_length=255)),
                (
                    "catagory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.catagory",
                    ),
                ),
                ("vendor", models.ManyToManyField(to="main_app.vendor")),
            ],
        ),
    ]
