# Generated by Django 4.2.3 on 2023-08-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='vendor',
            new_name='vendors',
        ),
    ]
