# Generated by Django 4.2.3 on 2023-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_rename_vendor_event_vendors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="pricing",
            field=models.CharField(),
        ),
    ]
