# Generated by Django 4.2.3 on 2023-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_vendor_event_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pricing',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='event',
            name='Category',
            field=models.CharField(choices=[('B', 'Bootcamp'), ('S', 'Social Event')], default='B', max_length=1),
        ),
    ]
